### ISSUE TITLE
Issue with 2.49.0 - 0% creation success rate

### ISSUE THREAD

**Issue by Playit3110** [PurpleI2P/i2pd#1971]
Hello I2Pd Team,
I have the issue that my node does not want to connect to the network. I am a I2Pd user for 3 years and it worked with version 2.49.0 untill recently. Now it doesn't connect anymore.

## What I did

1. I opened a port
2. I waited 24 hours for connections
3. I restarted the node

![grafik](https://github.com/PurpleI2P/i2pd/assets/38607319/baa1a0d0-cedf-4217-9c27-35a03da90683)

**Comment by Vort** [comment]
Try looking at log file - maybe it will contain some hints.

**Comment by Playit3110** [comment]
Had a look into the log:

```
Transports: no compatible address available
Router: Can't find floodfill to publish our RouterInfo
SSU: Send Exception: Invalid argument to x.x.x.x:xxxxx
```

**Comment by SergSel2006** [comment]
Your bootstrap process is failed. You might want to find reseed files or netdb from working router.
I guess you have changed reseed configuration or something like this. Check all configuration files.

**Comment by SergSel2006** [comment]
Oh, mine just did exactly what you said. I'm sure you have i2pd from Ubuntu repository. I've fixed mine by building from source.

**Comment by verdare** [comment]
I'm having the same issue, but with a different set of errors:
```
16:30:49@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:30:49@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:30:49@909/warn - NTCP2: SessionCreated read error: Connection reset by peer
16:30:50@909/warn - NTCP2: SessionCreated read error: Connection reset by peer
16:30:50@909/warn - NTCP2: SessionCreated read error: End of file
16:30:50@347/warn - SSU2: Session with [2001:0:14be:4c8:2cf5:23d4:a9e8:30dc]:16847 was not established after 5 seconds
16:30:50@909/warn - NTCP2: SessionCreated read error: End of file
16:30:50@909/warn - NTCP2: SessionCreated read error: End of file
16:30:50@347/warn - SSU2: Retry token is zero
16:30:50@140/warn - Transports: 15 ephemeral keys generated at the time
16:30:55@347/warn - SSU2: Session with 86.23.207.35:16847 was not established after 5 seconds
16:30:59@347/warn - SSU2: Session with [2a04:4a43:94ff:fbdc:3902:49ca:36d9:be0a]:27202 was not established after 5 seconds
16:31:01@21/error - I2CP: Can't receive header
16:31:01@483/warn - Transports: Session to peer VaX1TkvkeX5Ph03qBwYQWDzogN0fpiCZ9bcmSoMJFxw= has not been created in 15 seconds
16:31:01@483/warn - Transports: Session to peer Sla0qN4FXU1q1dyDD5vgMN64oKkGNmMY43GKuGg~m4Y= has not been created in 15 seconds
16:31:01@483/warn - Transports: Session to peer e-iYsLb8Vf6cl2CNdfkHBj~Q5mspiuSKuBvvlozQV2c= has not been created in 15 seconds
16:31:01@483/warn - Transports: Session to peer d4a0A94ZWe-7OLGUs-bsruccyYgmQgXXWicCg~rBwQI= has not been created in 15 seconds
16:31:01@483/warn - Transports: Session to peer 6uwuAIBG7iumXr7i~RFb2F-vDbtTf1kwcTo6GULYWfo= has not been created in 15 seconds
16:31:01@347/warn - SSU2: Session to yium-Sxj5uypx6ahRIztM8CRaF1BMKJz8FhHB8pslZo= already exists
16:31:01@347/warn - SSU2: Retry token is zero
16:31:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:04@347/warn - SSU2: Session with 2.178.171.8:9228 was not established after 5 seconds
16:31:04@347/warn - SSU2: Session with 71.212.123.81:25878 was not established after 5 seconds
16:31:04@347/warn - SSU2: Session with 87.219.14.31:39355 was not established after 5 seconds
16:31:04@347/warn - SSU2: Session with 88.196.217.214:3117 was not established after 5 seconds
16:31:04@347/warn - SSU2: Session with 156.57.27.44:30257 was not established after 5 seconds
16:31:05@909/warn - NTCP2: SessionCreated read error: Connection reset by peer
16:31:05@909/warn - NTCP2: SessionCreated read error: Connection reset by peer
16:31:05@909/warn - NTCP2: SessionCreated read error: End of file
16:31:05@909/warn - NTCP2: SessionCreated read error: End of file
16:31:06@347/warn - SSU2: Session with 150.95.141.46:10116 was not established after 5 seconds
16:31:06@347/warn - SSU2: Session with 49.13.155.229:17146 was not established after 5 seconds
16:31:06@347/warn - SSU2: Session with 46.188.104.138:10220 was not established after 5 seconds
16:31:06@347/warn - SSU2: Session with 96.126.98.194:20875 was not established after 5 seconds
16:31:06@347/warn - SSU2: Session with 89.58.17.228:17471 was not established after 5 seconds
16:31:06@347/warn - SSU2: Session with [2a05:3580:dc0b:1600:708f:9b3f:43dc:640c]:19642 was not established after 5 seconds
16:31:06@347/warn - SSU2: Session with [2a0a:4cc0:0:f0a:a45c:7aff:fe13:2781]:17471 was not established after 5 seconds
16:31:06@347/warn - SSU2: Session with [2a01:4f8:210:2073:192:168:1:16]:27553 was not established after 5 seconds
16:31:06@347/warn - SSU2: Session with [2001:1ad0:c4fe:504::11]:19357 was not established after 5 seconds
16:31:09@347/warn - SSU2: Session with [2a01:4f8:192:2053::2]:17696 was not established after 5 seconds
16:31:09@347/warn - SSU2: Retry token is zero
16:31:10@347/warn - SSU2: Session with 212.169.10.182:26504 was not established after 5 seconds
16:31:10@909/warn - NTCP2: SessionCreated read error: End of file
16:31:10@347/warn - SSU2: Session with [2a01:4f8:191:3386::2]:30377 was not established after 5 seconds
16:31:10@909/warn - NTCP2: SessionCreated read error: End of file
16:31:10@347/warn - SSU2: Retry token is zero
16:31:19@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:19@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:19@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:19@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:19@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:19@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:19@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:19@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:19@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:19@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:19@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:19@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:19@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:19@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:19@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:19@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:19@909/warn - NTCP2: SessionCreated read error: Connection reset by peer
16:31:19@347/warn - SSU2: Session with 109.156.63.74:17616 was not established after 5 seconds
16:31:19@347/warn - SSU2: Retry token is zero
16:31:20@909/warn - NTCP2: SessionCreated read error: End of file
16:31:20@909/warn - NTCP2: SessionCreated read error: Connection reset by peer
16:31:20@909/warn - NTCP2: SessionCreated read error: Connection reset by peer
16:31:20@347/warn - SSU2: Retry token is zero
16:31:20@909/warn - NTCP2: SessionCreated read error: End of file
16:31:20@909/warn - NTCP2: SessionCreated read error: End of file
16:31:24@347/warn - SSU2: Session with 71.79.145.162:35695 was not established after 5 seconds
16:31:25@347/warn - SSU2: Session with [2a07:e040:2:203::1]:28692 was not established after 5 seconds
16:31:25@347/warn - SSU2: Session with [2602:fc24:12:1609::1]:19584 was not established after 5 seconds
16:31:26@347/warn - SSU2: Retry token is zero
16:31:30@347/warn - SSU2: Session with 91.218.20.104:28692 was not established after 5 seconds
16:31:31@21/error - I2CP: Can't receive header
16:31:34@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:34@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:34@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:34@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:34@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:34@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:34@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:34@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:34@140/warn - Transports: 10 ephemeral keys generated at the time
16:31:34@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:34@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:34@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:34@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:34@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:34@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:34@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:34@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:34@909/warn - NTCP2: SessionCreated read error: Connection reset by peer
16:31:34@909/warn - NTCP2: SessionCreated read error: End of file
16:31:35@347/warn - SSU2: Retry token is zero
16:31:35@140/warn - Transports: 15 ephemeral keys generated at the time
16:31:39@347/warn - SSU2: Session with 185.21.217.48:22920 was not established after 5 seconds
16:31:43@347/warn - SSU2: Session with 212.220.202.62:29810 was not established after 5 seconds
16:31:46@483/warn - Transports: Session to peer 4HRRKOHWMU4mlKfxncRbE0kfZLkvgMfoSJgiUKUeSx8= has not been created in 15 seconds
16:31:46@483/warn - Transports: Session to peer 4fSdJKBERmOhQFdbT9v26qJillW6H17AXbZlvsOFV5M= has not been created in 15 seconds
16:31:49@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:49@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:49@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:49@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:49@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:49@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:49@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:49@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:49@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:49@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:49@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:49@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:49@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:49@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:49@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:31:49@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:31:49@909/warn - NTCP2: SessionCreated read error: End of file
16:31:49@347/warn - SSU2: Session with 103.228.53.8:11644 was not established after 5 seconds
16:31:49@909/warn - NTCP2: SessionCreated read error: End of file
16:31:49@909/warn - NTCP2: SessionCreated read error: Connection reset by peer
16:31:50@347/warn - SSU2: Retry token is zero
16:31:50@347/warn - SSU2: Session with [2001:0:14be:4c8:2cf5:23d4:a9e8:30dc]:16847 was not established after 5 seconds
16:31:51@347/warn - SSU2: Session with 85.227.197.55:35110 was not established after 5 seconds
16:31:51@909/warn - NTCP2: Session with 5aHAuOUTK6LL23-9LPfFQ2ldzlCJnq9nLmOrueHP5qA= already exists. Dropped
16:31:51@347/warn - SSU2: Session with 150.95.141.46:10116 was not established after 5 seconds
16:31:51@347/warn - SSU2: Session with 216.147.80.130:15668 was not established after 5 seconds
16:31:51@347/warn - SSU2: Session with 190.153.140.27:28008 was not established after 5 seconds
16:31:51@347/warn - SSU2: Session with 89.75.52.19:45875 was not established after 5 seconds
16:31:51@347/warn - SSU2: Session with [2a02:ed0:424a:1900::4]:20423 was not established after 5 seconds
16:31:51@347/warn - SSU2: Session with [2a01:4f9:c010:291f::2]:15314 was not established after 5 seconds
16:31:51@347/warn - SSU2: Session with [64:ff9b::59a3:d626]:13666 was not established after 5 seconds
16:31:51@347/warn - SSU2: Session with [2a04:4a43:94ff:fbdc:3902:49ca:36d9:be0a]:27202 was not established after 5 seconds
16:31:51@347/warn - SSU2: Session with [2a05:3580:dc0b:1600:708f:9b3f:43dc:640c]:19642 was not established after 5 seconds
16:31:54@347/warn - SSU2: Session with 104.33.14.195:32079 was not established after 5 seconds
16:31:54@347/warn - SSU2: Session with 79.97.156.165:27376 was not established after 5 seconds
16:31:55@347/warn - SSU2: Session with 86.23.207.35:16847 was not established after 5 seconds
16:31:56@347/warn - SSU2: Session with [2aa1::1]:35110 was not established after 5 seconds
16:32:01@21/error - I2CP: Can't receive header
16:32:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:32:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:32:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:32:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:32:04@140/warn - Transports: 11 ephemeral keys generated at the time
16:32:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:32:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:32:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:32:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:32:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:32:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:32:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:32:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:32:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:32:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:32:04@859/error - Tunnels: Can't select next hop for D1duHrc6Q6lMfYOj5Klr-dC6CoreFOruHeECL9c4F2E=
16:32:04@859/error - Tunnels: Can't create inbound tunnel, no peers available
16:32:04@347/warn - SSU2: Session with 84.71.237.239:34496 was not established after 5 seconds
16:32:04@347/warn - SSU2: Retry token is zero
16:32:04@347/warn - SSU2: Retry token is zero
16:32:04@909/warn - NTCP2: SessionCreated read error: End of file
16:32:05@347/warn - SSU2: Retry token is zero
16:32:05@909/warn - NTCP2: SessionCreated read error: End of file
16:32:05@909/warn - NTCP2: SessionCreated read error: Connection reset by peer
16:32:05@140/warn - Transports: 15 ephemeral keys generated at the time
16:32:05@909/warn - NTCP2: SessionCreated read error: End of file
```
![Screenshot 2024-01-04 at 16 41 33](https://github.com/PurpleI2P/i2pd/assets/136402843/d10d4c0f-fd42-4619-90b9-2c3c8e481cc7)

Java I2P still works, so I copied all of the floodfill nodes from that into i2pd. It didn't seem to help. (And to clarify, I'm _not_ running both at the same time.)

i2pd has worked for me before. It's the first time I've seen this issue. I'm running 2.49.0 on macOS, installed via MacPorts.

**Comment by Vort** [comment]
@verdare, you probably encountered bug #1988.
Possible solutions: adding `nettime.frompeers = false` to config file or updating to version built from latest commit (c5cab05a6b8690f3fd2442054c1475e06dc43640 at this time).

**Comment by verdare** [comment]
@Vort, thanks for the response. I tried adding the `nettime.frompeers = false` line to the config and restarting the daemon, but it didn't fix the issue; I'm still getting the same errors.

It starts with a tunnel creation rate of 10% and then quickly drops to 0%.

**Comment by Vort** [comment]
Did you added `nettime.frompeers = false` before first `[]` section of `i2pd.conf`?

**Comment by verdare** [comment]
Yes, I made sure to do that.

**Comment by Vort** [comment]
You may also try clearing `netDb` and `peerProfiles` directories.
NetDb is almost empty anyway at this moment.

**Comment by Vort** [comment]
@verdare: another idea: may it be that your OS updated OpenSSL to version 3.2?
In such case, i2pd update is also needed, to latest commit.

**Comment by verdare** [comment]
I'm actually investigating a possible directory permission issue that could be the cause. MacPorts configures `i2pd` to run under its own user, `_i2pd`. Those `netDb` and `peerProfiles` directories... Are they supposed to be under `/etc/i2pd` (or `/opt/local/etc/i2pd`, in my case)?

**Comment by Vort** [comment]
I don't know where files are stored on macOS.
But there should be subdirectories like `r0`, `r1`, `r2` with files like `routerInfo-....dat` and `profile-....txt`.
Please check OpenSSL version, it is more likely cause than file premissions.

**Comment by verdare** [comment]
> I don't know where files are stored on macOS. But there should be subdirectories like `r0`, `r1`, `r2` with files like `routerInfo-....dat` and `profile-....txt`. Please check OpenSSL version, it is more likely cause than file premissions.

Yep, I have OpenSSL 3.2.0. (And I found the correct directory where the addressbook and everything is.)

Damn, so I really need to pull the latest commit? When do you estimate OpenSSL 3.2 support will make it into the release version?

**Comment by Vort** [comment]
> Damn, so I really need to pull the latest commit? When do you estimate OpenSSL 3.2 support will make it into the release version?

You can try to use 2.50.1, but people reported that it crashes from time to time: #1997.

**Comment by verdare** [comment]
Okay, I built the latest commit on the `openssl` branch and switched the launch daemon script from `/opt/local/bin/i2pd` to `/usr/local/bin/i2pd`, and...

![Screenshot 2024-01-05 at 19 58 00](https://github.com/PurpleI2P/i2pd/assets/136402843/4e1e1452-a1ab-48f6-95b0-f98551f86331)
It's alive!

**Comment by agowa** [comment]
If someone still has this issue, please post your i2pd config file. Especially the three sections reseed, addressbook, and persist.

I think this issue could be related to un-commenting some (probably outdated) "default" values within the config. E.g. a comment within the config file still mentions the defunct `netdb.i2p2.no` (it says it's up for sell) as reseed source. And when I un-commented the self proclaimed default value it broke. Removing that line from the config fixed it.
I.E. there may be a difference between the actual default and what the config file lists as the default.

**Comment by r4sas** [comment]
Closing as outdated.
