### ISSUE TITLE
RouterInfo and Lease Set queries

### ISSUE THREAD

**Issue by sxlissxn** [PurpleI2P/i2pd#2081]
Hello, i'm conducting a simulation of I2pd in a self-contained environment. I'm having a few issues...
Currently it requires the simulation of the reseed server for boostraping and floodfill routers. Those entities requires the su3 files, which can be generated using some available tools. However, the su3 is constructed using the routerinfo.dat files, but the i2pd routers only generates the router.info files. Based on my research the routerinfo.dat file contains additional metadata.Thus are there ways to generate the router.info files and lease sets for a given number of simulated routers?

**Comment by Vort** [comment]
I don't know exact answer to your question.
However, as far as I know, I2P network can work witout reseeds, but you need to manually copy some starting routerinfos to netDb directories.
Here is some example code: https://codeberg.org/weko/i2pd-test-tools/src/commit/4663af6da3b511af1c066940a8535ea32cb15eaf/start_testnet.py.
Also you can look how reseeds work here:
https://github.com/PurpleI2P/pyseeder

**Comment by Vort** [comment]
Not enough nodes maybe?
You can look if nodes make connections at all:
`/debug - SSU2: Connecting to ip:port (hash)`
`/debug - NTCP2: Connecting to ip:port (hash)`

Also you need some nodes to have floodfill option enabled.

**Comment by sxlissxn** [comment]
i have simulated 15 i2pd routers, however, is the self-contained characteristic of my simulation tool causing the peer discovery issue? i have filled the NetDB, have floodfill and reseed server but i still get the same error.
![image](https://github.com/user-attachments/assets/ec9c04c1-39b7-42b6-b151-5202937ec9de)
![image](https://github.com/user-attachments/assets/486f2440-fb9b-49b9-a1fe-aeaafaec53c2)

**Comment by Vort** [comment]
How IP addresses for your nodes looks like?
Also it worth checking for connections as I said before.

There may be bugs in simulation tool of course, but first of all, more probable variants should be checked.

**Comment by sxlissxn** [comment]
for the ip addresse , now i am getting those errors, the nodes are not making connection at all:
![image](https://github.com/user-attachments/assets/6579fef4-61c9-4419-9aed-421c153f149e)

**Comment by Vort** [comment]
Try using "real" addresses like 1.1.1.1 - 1.1.1.254 for example.
I think simulation environment should allow it.

Not sure if errors will go away, there may be more problems, but changing IP addreses is worth to try.

**Comment by sxlissxn** [comment]
It does not work :(
For the peer selection, does it take it from the NetDB? 
Since i am not connecting to the internet for the simulation, i had to manually add files to the netDB and create the su3 files, is the fact that i changed the extension from router.info to routerInfo-Id.dat probably creating this issue?

**Comment by Vort** [comment]
> It does not work :(

Maybe it worth to try something simpler than i2pd first - web server (nginx) and web client (curl) for example.
Or custom made tcp server and client.

> For the peer selection, does it take it from the NetDB?

Yes, but problem in your case appears much earlier:
Node can't open its own ports.
It makes no sense trying to connect to other nodes in such case.
This problem should be solved first.

**Comment by sxlissxn** [comment]
> 
> Maybe it worth to try something simpler than i2pd first - web server (nginx) and web client (curl) for example. Or custom made tcp server and client.
> 
I've already tried those early this year. 

> Try using "real" addresses like 1.1.1.1 - 1.1.1.254 for example. I think simulation environment should allow it.
I was able to solve the binding problem by assigning ip addresses using the simulation configuration file instead of the i2pd configuration file. 
![image](https://github.com/user-attachments/assets/a0e76afb-1dc2-4403-b399-e1423af7b99e)
However, i'm still having issues with the peer connection and now i am facing  a new issue:
![image](https://github.com/user-attachments/assets/e7502769-bc50-4a5d-bee6-e1391deac398)

**Comment by Vort** [comment]
> However, i'm still having issues with the peer connection

Do you see `Connecting` messages like I mentioned eariler?

> and now i am facing a new issue:

I don't think this error is much important.
And it affects only SSU2.
NTCP2 should be unaffected.

**Comment by Vort** [comment]
Also I suggest to look at routerinfos inside of netdb directory for your nodes.
Do they have `host` and `port` specified? What `caps` they have?
![image](https://github.com/user-attachments/assets/f78c3148-d42e-4ce1-82d1-4b59aaba5cc2)

**Comment by sxlissxn** [comment]
![image](https://github.com/user-attachments/assets/0d93bddb-975e-4777-9487-eb37400028e9)

**Comment by Vort** [comment]
`PfG` caps are not right. Why transit is disabled? It should not be like that.
Also where this RI was located? In netdb of node with other IP (like 100.0.0.2)?

**Comment by sxlissxn** [comment]
this is the router.info found in the data directory for that specific i2pd router.I haven't enabled the *no transit*

**Comment by Vort** [comment]
> this is the router.info found in the data directory for that specific i2pd router

It should appear in netdb directory of other routers, in some way, either manually (which I suggest to try first) or with the help of reseeds. With different name, like this one: `netDb\r6\routerInfo-6NcDCoHU0H2TRBEANjcZaonkqPtYYn2wnCIHAfILZPE=.dat`. This name is made by hashing part of RI contents.

> I haven't enabled the no transit

Ok, maybe this situation will correct itself somehow (with simulations of longer durations for example).

**Comment by sxlissxn** [comment]
i added the routerInfo manually to the netDB.However, i though that "6NcDCoHU0H2TRBEANjcZaonkqPtYYn2wnCIHAfILZPE=" was the router ID and not hashed part of the RI content... I've set the simulation for 30 min, however, due to the errors in tunnel creations it lasts only 15-20 seconds

**Comment by Vort** [comment]
Router Ident is calculated with hashing.
I was saying it because if you have RI file of "unknown" router, you can calculate such ID without additional information.

> i added the routerInfo manually to the netDB

So other routers have this file?
They should try to make connections to this router then.

**Comment by Vort** [comment]
I made test by myself, with two virtual machines.
First machine, 100.0.0.1, hosted floodfill with such config:
```
bandwidth = P
floodfill = true
loglevel = debug

host = 100.0.0.1
port = 1024

[reseed]
urls =
yggurls =
```

Second virtual machine, 100.0.0.2, hosted regular node:
```
bandwidth = P
floodfill = false
loglevel = debug

[reseed]
urls =
yggurls =
```

After I placed floodfill (node1) RI into correct place, `i2pd_node2.zip\netdb\rK\routerInfo-k3Kki0MLyPKK-uhKZEosY80CM8AF~r8mupJxwsbMXQ8=.dat`, second node was able to start making connection:
```
17:03:59@332/debug - SSU2: Connecting to 100.0.0.1:1024 (k3Kk)
...
17:03:59@332/debug - SSU2: Block type 0 of size 4
17:03:59@332/debug - SSU2: Datetime
17:03:59@332/debug - SSU2: Block type 13 of size 6
17:03:59@332/debug - SSU2: Address
17:03:59@332/info - SSU2: Our external address is 100.0.0.2:10849
...
```

You can look at full logs in these archives:
[i2pd_node1.zip](https://github.com/user-attachments/files/16677076/i2pd_node1.zip)
[i2pd_node2.zip](https://github.com/user-attachments/files/16677072/i2pd_node2.zip)
Binaries are omitted to keep files small.

**Comment by sxlissxn** [comment]
Hello, I tried it tool on virtual machines, it works. I think the issue lies within the simulation tool itself and not within the i2pd configuration.

**Comment by Vort** [comment]
You may also check for time related problems.
If simulation have zero timestamps at the start, it may cause problems.

**Comment by sxlissxn** [comment]
The timestamp in my simulation seems fine.
The i2pd routers in my simulation are set up in such a way that it connects to the i2p network, however, is there a way to ensure that it does not connect to the i2p network but rather communicate with each other only (private network)?

**Comment by Vort** [comment]
> is there a way to ensure that it does not connect to the i2p network but rather communicate with each other only

By clearing extra RouterInfos in netdb directories and setting
```
[reseed]
urls =
yggurls =
```
on each node.

**Comment by sxlissxn** [comment]
Hello, I ended up dropping the simulation for vms simulation. Thanks a lot! However, i have a queation: Can i use the java version of the I2CP Api with a i2pd router or it works only on the java version of i2p?

**Comment by Vort** [comment]
I know that I2PSnark uses I2CP and can work both with i2pd and java i2p.
But I have no experience with them.

**Comment by sxlissxn** [comment]
For the routerInfo-Ident=.dat to be manually sent to netDbs, did you rename it mannualy or? Because, now that i have added more nodes into the simulation doing it this way, I am getting this error:
![image](https://github.com/user-attachments/assets/96ea5c64-7b32-4263-9e67-3593ed2befef)
I2pd is not starting.

**Comment by Vort** [comment]
I made it manually for my tests, but such sorting can be automated by writing tool for this task.

If you have reproduction steps for getting that crash, it may make sense to modify i2pd to prevent it from happening, even if crash happen because of wrong file placement.

**Comment by sxlissxn** [comment]
can you elaborate on this?

**Comment by sxlissxn** [comment]
If I use https://github.com/PurpleI2P/pyseeder on another vm, will it bootstrap them and place them in their correct place with their correct ident in the netDb?

**Comment by Vort** [comment]
> can you elaborate on this?

1. Router idents are obtained by hashing. Do you want to know what exactly needs to be hashed?
2. From your "core-dump" result I make conclusion that i2pd crashed. It should not happen. If you can explain how such crash can be reproduced on other computers, it may help to improve code.

**Comment by sxlissxn** [comment]
It crashed after i filled in the netDb

**Comment by Vort** [comment]
> If I use https://github.com/PurpleI2P/pyseeder on another vm, will it bootstrap them and place them in their correct place with their correct ident in the netDb?

Reseed works with already launched network.
If you are starting network from scratch, I doubt it will help much.

> It crashed after i filled in the netDb

netDb is filled regularly during node operation and no crashes happen.
Can you attach zipped contents of such netdb?

**Comment by sxlissxn** [comment]
![image](https://github.com/user-attachments/assets/bf1c6733-31d5-4ca4-8810-58937a59ce80)
[i2pd.zip](https://github.com/user-attachments/files/17006791/i2pd.zip)

**Comment by Vort** [comment]
I already see mistake.
`routerInfo--lGZb...` should be in `r-` directory, not in `rI`.

**Comment by sxlissxn** [comment]
I changed it... thanks for pointing it out. However, i still can't create tunnels , it is stuck at this:
![image](https://github.com/user-attachments/assets/59d004dc-b209-46a0-9aea-a4665f3db395)

**Comment by sxlissxn** [comment]
It activated then back to failed...

**Comment by Vort** [comment]
> it is stuck at this:

Absence of message is, most likely, because of default `loglevel`.
With `debug` level there will be more info.

> It activated then back to failed...

By activated you mean `established`?
Tunnel with how many hops was created?

Also how many connections to other nodes this particular nodes was able to establish?
With low amount of connected nodes there will be problems with creation of long (many hops) tunnels.

**Comment by sxlissxn** [comment]
I am getting this issue 
> > ![image](https://private-user-images.githubusercontent.com/105369657/358913049-e7502769-bc50-4a5d-bee6-e1391deac398.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjQ3ODYsIm5iZiI6MTcyNjQyNDQ4NiwicGF0aCI6Ii8xMDUzNjk2NTcvMzU4OTEzMDQ5LWU3NTAyNzY5LWJjNTAtNGE1ZC1iZWU2LWUxMzkxZGVhYzM5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxODIxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjhkMTVkNDkxZGE4ZGQwMGQ1ODU1ZTQzNjFjOGJiOGJiODk2YjRiNWEyYjVmOTVlMzc1ZmEyYmUxNDU5OGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VnLmt_N1upxsbtbpoj6w0BBrxGVaoosqK5wpeY0cntQ)





> For the routerInfo-Ident=.dat to be manually sent to netDbs, did you rename it mannualy or? Because, now that i have added more nodes into the simulation doing it this way, I am getting this error: ![image](https://private-user-images.githubusercontent.com/105369657/367601231-96ea5c64-7b32-4263-9e67-3593ed2befef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjQ3ODYsIm5iZiI6MTcyNjQyNDQ4NiwicGF0aCI6Ii8xMDUzNjk2NTcvMzY3NjAxMjMxLTk2ZWE1YzY0LTdiMzItNDI2My05ZTY3LTM1OTNlZDJiZWZlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxODIxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjE5NzcxMmE3OTgxZTE1ZmJlNDBkNjY2OTkyNjA5YzYxMTUwZDAzNmY3MjNhYzEwM2Y1OWExYTQ2MmU3NDFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lLwOpECdbTtxz4njccD0GbuWnsm_ylwRfBLB3CTHUSs) I2pd is not starting.

and this issue as well

**Comment by sxlissxn** [comment]
> For the routerInfo-Ident=.dat to be manually sent to netDbs, did you rename it mannualy or? Because, now that i have added more nodes into the simulation doing it this way, I am getting this error: ![image](https://private-user-images.githubusercontent.com/105369657/367601231-96ea5c64-7b32-4263-9e67-3593ed2befef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjQ3ODYsIm5iZiI6MTcyNjQyNDQ4NiwicGF0aCI6Ii8xMDUzNjk2NTcvMzY3NjAxMjMxLTk2ZWE1YzY0LTdiMzItNDI2My05ZTY3LTM1OTNlZDJiZWZlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxODIxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjE5NzcxMmE3OTgxZTE1ZmJlNDBkNjY2OTkyNjA5YzYxMTUwZDAzNmY3MjNhYzEwM2Y1OWExYTQ2MmU3NDFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lLwOpECdbTtxz4njccD0GbuWnsm_ylwRfBLB3CTHUSs) I2pd is not starting.

Im still getting this issue

**Comment by Vort** [comment]
I though you meant `failed` tunnels.

`failed` service means that crash is still there and it is not related to wrong location of RouterInfo in `netdb`.
